name: C++ Vehicle Counter CI

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: vcpkg_installed
        key: ${{ runner.os }}-vcpkg-dependencies-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-dependencies-

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install opencv
        ./vcpkg/vcpkg install nlohmann-json

    - name: Upload vcpkg cache
      uses: actions/upload-artifact@v3
      with:
        name: vcpkg-cache
        path: vcpkg_installed

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download vcpkg cache
      uses: actions/download-artifact@v3
      with:
        name: vcpkg-cache

    - name: Set up OpenCV and nlohmann/json with vcpkg
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build --parallel

    - name: Run the application
      run: ./build/vehicle_counter_opencv/src/vehicle_counter_opencv

    - name: Clean up
      run: |
        rm -rf build
