name: C++ Vehicle Counter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies (vcpkg)
      run: |
        sudo apt update
        sudo apt install -y curl zip unzip tar
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install nlohmann-json opencv4
    
    - name: Set up OpenCV
      run: sudo apt install -y libopencv-dev  # Ensure this is included for OpenCV installation

    - name: Configure the project with CMake
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build the application
      run: cmake --build build

    - name: Run the application
      run: ./build/vehicle_counter_opencv/src/vehicle_counter_opencv

    - name: Clean up
      run: |
        rm -rf build

