name: C++ Vehicle Counter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # Cache vcpkg dependencies to speed up builds
    - name: Cache vcpkg
      uses: actions/cache@v3
      with:
        path: vcpkg_installed
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

        # Install vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install opencv nlohmann-json

    - name: Set up OpenCV and nlohmann/json with vcpkg
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build

    - name: Run the application
      run: ./build/vehicle_counter_opencv/src/vehicle_counter_opencv

    - name: Clean up
      run: |
        rm -rf build

